# Generated by Django 5.2.6 on 2025-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_is_on_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
